musicTribes/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up', views.signup,name='signup'),
    path('<int:user_id>', views.profile, name="profile"),
    path('editprofile',views.editprofile, name="editprofile"),
    path('editprofile/changepassword',views.changepassword, name="changepassword"),
    path('editprofile/extendededit',views.extendededit, name="extendededit")
]

musicTribes/app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name='index'),
    path('create_tribe', views.create_tribe, name='create_tribe'),
    path('<int:tribe_id>/', views.tribe, name='tribe'),
    path('<int:tribe_id>/join', views.join, name='join'),
    path('<int:tribe_id>/leave', views.leave, name='leave'),
    path('<int:tribe_id>/kick/<int:user_id>', views.kick, name='kick'),
    path('<int:tribe_id>/create_playlist', views.create_playlist, name='create_playlist'),
    path('<int:tribe_id>/update_tribe/', views.update_tribe, name='update_tribe'),
    path('<int:tribe_id>/add_message', views.add_message, name='add_message'),
    path('<int:tribe_id>/playlist/<int:playlist_id>/<int:song_id>/add_comment', views.add_comment, name='add_comment'),
    path('<int:tribe_id>/delete_message/<int:message_id>', views.delete_message, name='delete_message'),
    path('<int:tribe_id>/playlist/<int:playlist_id>', views.playlist, name='playlist'),
    path('<int:song_id>/delete_song', views.delete_song, name='delete_song'),
    path('<int:comment_id>/delete_comment', views.delete_comment, name='delete_comment'),
    path('<int:song_id>/like', views.likebtn, name='likebtn'),
    path('playlist/<int:playlist_id>/create_song', views.create_song, name='create_song'),
    path('playlist/<int:playlist_id>/update_playlist', views.update_playlist, name='update_playlist'),
    path('playlist/<int:playlist_id>/delete_playlist', views.delete_playlist, name='delete_playlist'),
]

musicTribes/musicTribes/urls.py
from django.contrib import admin
from django.urls import include, path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include ('accounts.urls')),
    path('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('tribes/', include('app.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

musicTribes/app/templates/app/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Music Tribes</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/app/css/base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://kit.fontawesome.com/15e49b5581.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>

  <body>

    <div class="navbar-container">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <img src="{% static '/app/chieftain-logo.png' %}" width="40" height="40" alt="">
      <div class="navbar-brand" href="#">MusicTribes</div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'app:index'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link " href="{% url 'app:create_tribe' %}">Add new tribe</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome, {{user.username}}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'accounts:editprofile'%}">Edit profile</a>
            </div>
          </li>
        </ul>
        <a class="nav-link float-right" href="{% url 'logout' %}">Log out</a>      
        {% else %}
        <a class="nav-link float-right" href="{% url 'login' %}">Log in</a>
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
        {% endif %}
      </div>
    </nav>
  </div>

    <div class="container-main">
      {% block content %}
      {% endblock %}
    </div><!-- /.container -->
  </body>
</html>

musicTribes/app/templates/app/changepassword.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="container all-forms">
    <div class="row">
        <div class="col-md-12"><h2 class="text-center">Change Password</h2></div>
    </div>
        <form method="post" accept-charset="utf-8">
            {% csrf_token %}
            
            {%include 'includes/bs4_form.html' with form=form %}
            <div class="row">
            <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
        </form>
</div>
{% endblock %}

musicTribes/app/templates/app/create_playlist.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="container all-forms">
    <div class="row">
            <div class="col-md-12"><h2 class="text-center">Create Playlist</h2></div>
        </div>
            <form method="post" accept-charset="utf-8">
                {% csrf_token %}
                
                {%include 'includes/bs4_form.html' with form=form %}
                <div class="row">
                <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
            </form>
</div>
{% endblock %}

musicTribes/app/templates/app/create_song.html
{% extends 'app/base.html' %}
{% load static %}
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% block content %}
{{form.media}}
<div class="container all-forms">
    <div class="row">
            <div class="col-md-12"><h2 class="text-center">Create Song</h2></div>
        </div>
            <form method="post" accept-charset="utf-8">
                {% csrf_token %}
                
                {%include 'includes/bs4_form.html' with form=form %}
                <div class="row">
                <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
            </form>
</div>
{% endblock %}

musicTribes/app/templates/app/create_tribe.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container all-forms">
    <div class="row">
            <div class="col-md-12"><h2 class="text-center">Create Tribe</h2></div>
        </div>
            <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
                {% csrf_token %}
                
                {%include 'includes/bs4_form.html' with form=form %}
                <div class="row">
                <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
            </form>
</div>
{% endblock %}

musicTribes/app/templates/app/edituser.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container all-forms">
    <div class="edit-user-header">
        {% if profile.avatar_img %}
            <img class="avatar" src ="{{profile.avatar_img.url}}"></img>
        {% else %}
            <img class="avatar" src ="{{profile.avatarurl}}"></img>
        {% endif %}
        <h1 style="display:inline;font-family: 'Noto Serif', serif;">{{user.username}}</h1>
        <p style="font-family: 'Noto Serif', serif;">{{profile.bio}}</p>
    </div>
    <div class="edit-user-optional">
        <a href="{%url 'accounts:changepassword' %}" class="btn btn-info">Change password</a>
        <a href="{%url 'accounts:extendededit' %}" class="btn btn-info">Change bio and avatar</a>
    </div>
    <form method="post" accept-charset="utf-8">
        {% csrf_token %}
        
        {%include 'includes/bs4_form.html' %}
        <div class="row">
        <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
    </form>
</div>
{% endblock %}

musicTribes/app/templates/app/extendededit.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="container all-forms">
    <div class="row">
        <div class="col-md-12"><h2 class="text-center">Change avatar and bio</h2></div>
    </div>
        <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
            {% csrf_token %}
            
            {%include 'includes/bs4_form.html' with form=form %}
            <div class="row">
            <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
        </form>
</div>
{% endblock %}

musicTribes/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    {%if not user.is_authenticated%}
        {% for tribe in tribes %}    
            <div class="card bg-light text-dark">
                <div class="card-body">
                    {%if tribe.logo_img%}
                        <img class = "tribe-logo" src="{{tribe.logo_img.url}}"></img>
                    {% else %}
                        <img class = "tribe-logo" src="{{tribe.logourl}}"></img>
                    {% endif%}
                    <a href="{% url 'app:tribe' tribe.id %}"><h1 class="tribe-name" style="display:inline;">{{ tribe.name }}</h1></a>
                    {% if tribe.author.avatar_img %}
                        <img class="card-img float-right" src="{{tribe.author.avatar_img.url}}" alt="Card image">
                    {% else %}
                        <img class="card-img float-right" src="{{tribe.author.avatarurl}}" alt="Card image">
                    {% endif %}
                    <h4 class ="text-muted float-right" style="display:inline;">{{tribe.created_by}}</h4>
                    
                </div>
            </div>
        {% empty %}
            <h2 style="margin:2%;">No tribes yet.</h2>
        {% endfor %}  
    {%else%}
        <h1 style="font-family: 'Noto Serif', serif;margin:2%;">Chieftain tribes</h1>
        {%for chieftain_tribe in chieftain_tribes%}
            <div class="card bg-light text-dark">
                <div class="card-body">
                    {%if chieftain_tribe.logo_img%}
                        <img class = "tribe-logo" src="{{chieftain_tribe.logo_img.url}}"></img>
                    {% else %}
                        <img class = "tribe-logo" src="{{chieftain_tribe.logourl}}"></img>
                    {% endif%}
                    <a href="{% url 'app:tribe' chieftain_tribe.id %}"><h1 class="tribe-name" style="display:inline;">{{ chieftain_tribe.name }}</h1></a>
                    {% if chieftain_tribe.author.avatar_img %}
                        <img class="card-img float-right" src="{{chieftain_tribe.author.avatar_img.url}}" alt="Card image">
                    {% else %}
                        <img class="card-img float-right" src="{{chieftain_tribe.author.avatarurl}}" alt="Card image">
                    {% endif %}
                    <h4 class ="text-muted float-right" style="display:inline;">{{chieftain_tribe.created_by}}</h4>
                    
                </div>
            </div>
         
            {% empty %}
            <h5>You aren't a chieftain of any tribes. Create a new tribe to become a chieftain.</h5> 
        {% endfor %}
        <h1 style="font-family: 'Noto Serif', serif; margin:2%;">Member tribes</h1>
        {% for member_tribe in member_tribes%}
            {% if not member_tribe in chieftain_tribes%}
                <div class="card bg-light text-dark">
                    <div class="card-body">
                        {%if member_tribe.logo_img%}
                            <img class = "tribe-logo" src="{{member_tribe.logo_img.url}}"></img>
                        {% else %}
                            <img class = "tribe-logo" src="{{member_tribe.logourl}}"></img>
                        {% endif%}
                        <a href="{% url 'app:tribe' member_tribe.id %}"><h1 class="tribe-name" style="display:inline;">{{ member_tribe.name }}</h1></a>
                        {% if member_tribe.author.avatar_img %}
                            <img class="card-img float-right" src="{{member_tribe.author.avatar_img.url}}" alt="Card image">
                        {% else %}
                            <img class="card-img float-right" src="{{member_tribe.author.avatarurl}}" alt="Card image">
                        {% endif %}
                        <h4 class ="text-muted float-right" style="display:inline;">{{member_tribe.created_by}}</h4>
                    </div>
                </div>
           {% endif %}
        {%empty%}
        <h5 >You aren't a member of any tribes.</h5>
        {% endfor %}
        <h1 style="font-family: 'Noto Serif', serif;margin:2%;">Discover tribes</h1>
        {% for discover_tribe in discover_tribes%}
        <div class="card bg-light text-dark">
            <div class="card-body">
                {%if dicover_tribe.logo_img%}
                    <img class = "tribe-logo" src="{{discover_tribe.logo_img.url}}"></img>
                {% else %}
                    <img class = "tribe-logo" src="{{discover_tribe.logourl}}"></img>
                {% endif%}
                <a href="{% url 'app:tribe' discover_tribe.id %}"><h1 class="tribe-name" style="display:inline;">{{ discover_tribe.name }}</h1></a>
                {% if discover_tribe.author.avatar_img %}
                    <img class="card-img float-right" src="{{discover_tribe.author.avatar_img.url}}" alt="Card image">
                {% else %}
                    <img class="card-img float-right" src="{{discover_tribe.author.avatarurl}}" alt="Card image">
                {% endif %}
                <h4 class ="text-muted float-right" style="display:inline;">{{discover_tribe.created_by}}</h4>
            </div>
        </div>
        {%empty%}
        <h5 >Nothing here yet.</h5>
        {% endfor %}
    {%endif%} 
</div>
{% endblock %}

musicTribes/app/templates/app/playlist.html
{% extends 'app/base.html' %}
{%load static%}
{% block content %}

    
<div class="jumbotron d-flex jumbo">
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                {% if is_member_of_tribe %}
                {% include "includes/add_song_button.html" with playlist=playlist %}
                {% endif %} 
            </div>
            <div class="col-lg-7">

            </div>
            <div class="col-2">
                <h4>Created by: {{playlist.creator}}</h4>
                <h6>{{playlist.created_at}}</h6>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid playlist-main">
    <div class="row">
        <div class ="col-5 description-container">
            <h1 id="playlist-name"style="font-family: 'Noto Serif', serif;font-weight:bold;margin:2%;">{{playlist.name}}</h1>
            <h5 style="font-family: 'Noto Serif', serif;display:inline;margin:2%;">Description: </h5>
            <p style="font-family: 'Noto Serif', serif;display:inline;">{{playlist.description}}</p>
        </div>
        <div class ="col-7 songs-container">
            {%include "app/songs.html" with song_with_likes=song_with_likes%}
        <!--#songs-container-->
        </div>
    </div>
</div>

<script>
function showComments() {

  if (event.srcElement.nextElementSibling.style.display === "none") {
    event.srcElement.nextElementSibling.style.display = "block";
  } else {
    event.srcElement.nextElementSibling.style.display = "none";
  }
} 
</script>               
{% endblock %}
  

musicTribes/app/templates/app/songs.html
{% load static %}
<h1 style="font-family: 'Noto Serif', serif;margin:2%;">Songs</h1>
{% for song,like,like_count in songs_with_likes %}
<div class="card bg-light text-dark">
    <div class="card-body">
        <div class ="row">
            <div class="col-8">
                <h4 style="display:inline;font-family: 'Arimo', sans-serif; font-weight:600;">{{ song.artist }} - {{ song.title }} {{song.song_duration|time:"H:i"}} </h4>
            </div>
            <div class="col-1">
                <a href="{{song.url}}" class="btn btn-info" target="_blank"><i class="fas fa-play fa-lg"></i></a>
            </div>
            <div class="col-3 d-flex justify-content-center">
                {% if user == playlist.creator.user or user.is_superuser or user == tribe.chieftain or user.profile == song.creator%}
                    {% include "includes/delete_song_button.html" with song=song %}
                {% endif %}
                {% if is_member_of_tribe or user.profile == tribe.chieftain%}
                    {% if like %}
                        {% include "includes/dislike_button.html" with song=song %}
                    {% else %}
                        {% include "includes/like_button.html" with song=song %}
                    {% endif %}
                {% else %}
                    <h5 style="margin-left:3%;margin-top:1%;">Likes: </h5>
                {% endif %}  
                <h5 style="margin-left:3%;margin-top:1%;">{{ like_count }}</h5>
            </div>
        </div>
        
        <div class="comments-container">
            <button class="btn btn-basic" id="btn-comments" onclick="showComments()">Toggle comments...</button>
            <div class="comments">
                    {% for comment in comments %}
                        {% if comment.song == song %}
                                <p class="comment">{{comment.text}}</p>
                                <div class="card-footer">
                                
                                    {% if comment.user.avatar_img %}
                                        <img class = "avatar-mini" src="{{comment.user.avatar_img.url}}"></img>
                                    {% else %}
                                        <img class = "avatar-mini" src="{{comment.user.avatarurl}}"></img>
                                    {% endif %}
                                        <p style="display:inline;">{{comment.user}}, {{comment.created_at}}</p>
                                    {% if tribe.chieftain == comment.user %}
                                        <img src="{% static '/app/chieftain-logo.png' %}" width="20" height="20" alt=""></img>
                                    {% endif %}
                                    {% if user.is_superuser or user == tribe.chieftain or user.profile == comment.user %}
                                    {% include "includes/delete_comment_button.html" with comment=comment %}
                                    {% endif %}
                                </div>
                        {% endif %}
                    {% endfor %}
                    {% if user.is_authenticated%}  
                        {% if is_member_of_tribe %}
                            <form action="{% url 'app:add_comment' tribe_id=tribe.id playlist_id=playlist.id song_id=song.id %}" accept-charset="utf-8" method = "POST"  style="text-align:center;">
                                    {% csrf_token %}
                                    {% include 'includes/bs4_form.html' with form=form %}
                                    <input type="submit" value="Comment" class="btn btn-primary">
                            </form>
                        {% endif %}
                    {%endif%}
                
                            </div>
                
    </div>
    <!--#Card-body-->
    </div>
<!--#Card-->
</div>
{%empty%}
<h5>Playlist is empty.</h5>
{% endfor %}

musicTribes/app/templates/app/tribe.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron">
    <div class="container-fluid">
        <div class="row">
            <div class="col-3 d-flex ">
                    {% if user.username != tribe.created_by and is_member_of_tribe and user.is_authenticated %}
                    <div class = "joined-container float-right" style="display:inline; margin-right:3%;">
                        <h2 style="display:inline;">Joined</h2>
                        <i class="fa fa-check" aria-hidden="true"></i>
                    </div>
                    {% endif %}
                    {% if user.username == tribe.created_by%}
                    {% include "includes/update_tribe_button.html" with playlist=playlist %}
                    {% endif %}
                    {% if user.username != tribe.created_by and not is_member_of_tribe and user.is_authenticated %}
                    {% include 'includes/join_button.html' with tribe=tribe %}
                    {% endif %}

                    {% if user.profile != tribe.chieftain and is_member_of_tribe and user.is_authenticated %}
                    {% include 'includes/leave_tribe_button.html' with tribe=tribe %}
                    {% endif %}

                    {% if user.is_authenticated and is_member_of_tribe %}
                    {% include "includes/create_playlist_button.html" %}
                    {% endif %}
    
            </div>
            <div class="col-3 d-flex justify-content-center">
                {%if tribe.logo_img%}
                    <img class = "tribe-logo" src="{{tribe.logo_img.url}}"></img>
                {% else %}
                    <img class = "tribe-logo" src="{{tribe.logourl}}"></img>
                {% endif%}
                <h1 style="text-align:center;font-family: 'Noto Serif', serif;font-weight:bold; color:#3c3a3a;">{{ tribe.name }}</h1>
            </div>
            <div class="col-3"></div>
        
            <div class="col-3 d-flex justify-content-center">
                <h2 class="text-muted">Chieftain: {{ tribe.created_by }} </h2>
                {% if tribe.chieftain.avatar_img %}
                    <img class = "avatar" src="{{tribe.chieftain.avatar_img.url}}"></img>
                {% else %}
                    <img class = "avatar" src="{{tribe.chieftain.avatarurl}}"></img>
                {% endif%}
            </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid tribe-main-container">
    <div class="row">
        <div class="col-2">
            <div class ="members-container">
            <h1 style="border-bottom: solid gray 1px; text-align:center;padding:2%;">Members</h1>
            {% for tribe_member in tribe_members %}
            <div class="edit-user-header" style="display:flex;" >
                {%if tribe_member.avatar_img%}
                    <img class = "avatar" src="{{tribe_member.avatar_img.url}}"></img>
                {% else %}
                    <img class = "avatar" src="{{tribe_member.avatarurl}}"></img>
                {% endif%}
                <h2 style="display:inline;">{{tribe_member}}</h2>
                {% if is_chieftain and not tribe_member == tribe.chieftain %}
                    {% include "includes/kick_member_button.html" with tribe=tribe user=tribe_member %}
                {% endif %}
            </div>
        
            {%empty%}
            <h5 class="text-muted">This tribe has no members yet.</h5>
        
        {% endfor %}
            </div>
        </div>

        <div class="col-7">
            <h1 style="margin:2%;">Playlists</h1>
            
            {% for playlist in playlists %}
                
                <div class="card bg-light text-dark">
                    <div class="card-body row">
                        <div class="col-10">
                            <a href="{% url 'app:playlist' tribe_id=tribe.id playlist_id=playlist.id %}"><h2 style="font-family: 'Noto Serif', serif;">{{ playlist.name }}</h2></a>
                            <p class="text-muted">{{ playlist.description }}</p>
                        </div>
                        <div class="col-2">
                            {% if user == playlist.creator.user or user.is_superuser or user == tribe.chieftain %}
                            {% include "includes/update_playlist_button.html" with playlist=playlist %}
                            {% include "includes/delete_playlist_button.html" with playlist=playlist %}
                            {% endif %}
                        </div>
                    </div>
                </div> 
                {%empty%}
                <h5>Nothing here yet.</h5>
                {% endfor %}                      
        </div>

        <div class="col-3">
        <h1 style="text-align:center;margin:2%;">Chatbox</h1>
            <div class ="messages-container">

                {% for message in messages %}
                <div class="card bg-basic">

                    <p class="message">{{message.text}}</p>
            
                    <div class="card-footer">
                        {%if message.user.avatar_img%}
                            <img class = "avatar-mini" src="{{message.user.avatar_img.url}}"></img>
                        {% else %}
                            <img class = "avatar-mini" src="{{message.user.avatarurl}}"></img>
                        {% endif %}
                            <p style="display:inline;">{{message.user}}, {{message.created_at}}</p>
                        {% if tribe.chieftain == message.user %}
                            <img src="{% static '/app/chieftain-logo.png' %}" width="20" height="20" alt="">
                        {% endif %}
                        {% if tribe.chieftain == user.profile or user.is_superuser%}
                            {% include 'includes/delete_message_button.html' with message=message%}
                        {% endif %}
                    </div>
                </div> 
                {%empty%}
                <h5 style="color:#3a3c3e; text-align:center;" >Be the first one to post a message!</h5>
                {% endfor %}  
            </div>
            <div>
            {% if user.is_authenticated %}
                    <form action="{% url 'app:add_message' tribe.id %}" accept-charset="utf-8" method = "POST"  style="text-align:center;">
                            {% csrf_token %}
                            {% include 'includes/bs4_form.html' with form=form %}
                            <input type="submit" value="Post message" class="btn btn-primary">
                        
                    </form>
                {%endif%}
            </div>
        </div>

    <!--#row-->
    </div>
</div>

{% endblock %}

musicTribes/app/templates/app/update_playlist.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="row">
        <div class="col-md-12"><h2 class="text-center">Update Playlist</h2></div>
    </div>
        <form method="post" accept-charset="utf-8">
            {% csrf_token %}
            
            {%include 'includes/bs4_form.html' with form=form %}
            <div class="row">
            <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
            </form>
{% endblock %}

musicTribes/app/templates/app/update_tribe.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="container">
<div class="row">
        <div class="col-md-12"><h2 class="text-center">Update Tribe</h2></div>
    </div>
        <form method="post" accept-charset="utf-8">
            {% csrf_token %}
            
            {%include 'includes/bs4_form.html' with form=form %}
            <div class="row">
            <div class="col-md-8 mx-auto"><input type="submit" value="Save" class="btn btn-primary"></div>
            </form>
</div>
{% endblock %}