musicTribes/app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name='index'),
    path('create_tribe', views.create_tribe, name='create_tribe'),
    path('<int:tribe_id>/', views.tribe, name='tribe'),
    path('<int:tribe_id>/join', views.join, name='join'),
    path('<int:tribe_id>/leave', views.leave, name='leave'),
    path('<int:tribe_id>/kick/<int:user_id>', views.kick, name='kick'),
    path('<int:tribe_id>/create_playlist', views.create_playlist, name='create_playlist'),
    path('<int:tribe_id>/update_tribe/', views.update_tribe, name='update_tribe'),
    path('<int:tribe_id>/add_message', views.add_message, name='add_message'),
    path('<int:tribe_id>/playlist/<int:playlist_id>/<int:song_id>/add_comment', views.add_comment, name='add_comment'),
    path('<int:tribe_id>/delete_message/<int:message_id>', views.delete_message, name='delete_message'),
    path('<int:tribe_id>/playlist/<int:playlist_id>', views.playlist, name='playlist'),
    path('<int:song_id>/delete_song', views.delete_song, name='delete_song'),
    path('<int:comment_id>/delete_comment', views.delete_comment, name='delete_comment'),
    path('<int:song_id>/like', views.likebtn, name='likebtn'),
    path('playlist/<int:playlist_id>/create_song', views.create_song, name='create_song'),
    path('playlist/<int:playlist_id>/update_playlist', views.update_playlist, name='update_playlist'),
    path('playlist/<int:playlist_id>/delete_playlist', views.delete_playlist, name='delete_playlist'),
]

musicTribes/musicTribes/urls.py
from django.contrib import admin
from django.urls import include, path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include ('accounts.urls')),
    path('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('tribes/', include('app.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

musicTribes/app/templates/includes/add_message.html
<form action="post" accept-charset="utf-8">
    {% csrf_token %}
    
    <input type="textarea">
    <div class="row">
    <div class="col-md-8 mx-auto"><input type="submit" value="Post" class="btn btn-primary"></div>
    </div>
    
</form>

musicTribes/app/templates/includes/add_song_button.html
<form action="{% url 'app:create_song' playlist.id %}" method ="post"
    role="form"
    class="form-inline float-left">
    {% csrf_token %}
    <input type="submit" value="Add Song" class="btn btn-success">
</form>

musicTribes/app/templates/includes/bs4_form.html
{% load widget_tweaks %}
{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
        
{% endfor %}

            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}

            {% for field in form.visible_fields %}
                <div class="row form-group">
                    <div class="col-md-8 controls mx-auto">
                    {{ field.label_tag }}

                    {% if form.is_bound %}
                        {% if field.errors %}
                            {% render_field field class="form-control is-invalid" %}
                            {% for error in field.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% endfor %}
                            {% else %}
                            {% render_field field class="form-control is-valid" %}
                        {% endif %}
                        {% else %}
                        {% render_field field class="form-control" %}
                    {% endif %}

                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            </div>
            {% endfor %}

musicTribes/app/templates/includes/create_playlist_button.html
<div>
    <form action="{% url 'app:create_playlist' tribe_id=tribe.id %}" method="POST" role="form">
        {% csrf_token %}
        <input type="submit" value="Create Playlist" class="btn btn-info">
    </form>
</div>

musicTribes/app/templates/includes/delete_comment_button.html
<form action="{% url 'app:delete_comment' comment.id %}" method="POST" role="form" class="form-inline float-right">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-sm"style="border-radius:90%;margin-top:2%;"><i class="fas fa-minus"></i></button>
</form>

musicTribes/app/templates/includes/delete_message_button.html
<form action="{% url 'app:delete_message' tribe_id=tribe.id message_id=message.id %}" method="POST" role="form" style="display:inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-sm float-right" style="border-radius:100%;margin-top:2%;"><i class="fas fa-minus"></i></button>
</form>

musicTribes/app/templates/includes/delete_playlist_button.html
<div>
    <form action="{% url 'app:delete_playlist' playlist.id %}" method="POST" role="form" class="form-inline float-left">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
</div>

musicTribes/app/templates/includes/delete_song_button.html
    <form action="{% url 'app:delete_song' song.id %}" method="POST" role="form" class="form-inline float-left">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger btn-sm gen-buttons">
    </form>

musicTribes/app/templates/includes/dislike_button.html
<form action="{% url 'app:likebtn' song.id %}" method ="post" role="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger"><i class="fa fa-thumbs-o-down"></i></button>
</form>

musicTribes/app/templates/includes/join_button.html
<form action="{% url 'app:join' tribe.id %}" method ="post"
    role="form"
    class="form-inline float-left">
    {% csrf_token %}
    <input type="submit" value="Join Tribe" class="btn btn-success gen-buttons">
</form>

musicTribes/app/templates/includes/kick_member_button.html
<form action="{% url 'app:kick' tribe_id=tribe.id user_id=tribe_member.id %}" method ="post" role="form">
    {% csrf_token %}
    <input type="submit" value="Kick" class="btn btn-danger" style="margin-left:100%;">
</form>

musicTribes/app/templates/includes/leave_tribe_button.html
<form action="{% url 'app:leave' tribe.id %}" method ="post" role="form">
    {% csrf_token %}
    <input type="submit" value="Leave tribe" class="btn btn-danger">
</form>

musicTribes/app/templates/includes/update_playlist_button.html
<div>
    <form action="{% url 'app:update_playlist' playlist.id %}" method="POST" role="form" class="form-inline float-left">
        {% csrf_token %}
        <input type="submit" value="Edit" class="btn btn-info">
    </form>
</div>

musicTribes/app/templates/includes/update_tribe_button.html
<div>
    <form action="{% url 'app:update_tribe' tribe.id %}" method="POST" role="form" class="form-inline float-left">
        {% csrf_token %}
        <input type="submit" value="Edit tribe" class="btn btn-info" style="margin-left:-2%">
    </form>
</div>